### ISSUE TITLE
How to make it faster?

### ISSUE THREAD

**Issue by NPattanaik1** [bfolkens/py-market-profile#5]
I have a csv file which has more than 8000 rows, when I apply this code to my whole dataframe it relatively takes more than 1min. applying the below code:

```
def mkp(df, window=50, mode='tpo', tick_size=1):
    x = list()
    for i in range(0, df.shape[0] - window -1):
        dfp = df[i:i+window]
        mp = MarketProfile(dfp, mode=mode, tick_size=tick_size)
        mp_slice = mp[dfp.index.min() : dfp.index.max()].as_dict()
        x.append(mp_slice)
    return x
```

Can we make it faster by numba or any other tool?

**Comment by bfolkens** [comment]
I can look into some optimizations, yes - are you able to share your data?

**Comment by NPattanaik1** [comment]
Here is the link to download the data:
[https://github.com/FrankyJ578/LSTM-stock-prediction/blob/master/data/A.csv](url)

**Comment by bfolkens** [comment]
@Niranajn006 - can you send over the code snippet you're using to load this up and run the report you mentioned?  I take it the code above is involved as part of it, but I want to get a quick picture of what's going on so I can repro on my side.

**Comment by Niranajn006** [comment]
below is the whole code to load market profile output dictionary back to the pandas.
`def mp_dict(mp_slice, w):
    ln_keys = ['lvn_1_' + str(w), 'lvn_vol_1_' + str(w), 'lvn_2_' + str(w), 'lvn_vol_2_' + str(w)] #low nodes keys
    hn_keys = ['hvn_1_' + str(w), 'hvn_vol_1_' + str(w), 'hvn_2_' + str(w), 'hvn_vol_2_' + str(w)] #High node keys
    ln, hn = mp_slice['lvn'], mp_slice['hvn'] #ln and hn value in mp_slice
    del mp_slice['lvn'] #delete
    del mp_slice['hvn']
    ln = sorted(ln.items(), key=lambda kv: kv[1])
    hn = sorted(hn.items(), key=lambda kv: kv[1])
    hn = hn[::-1]
    ln = dict(zip(ln_keys,([x for sl in ln for x in sl]+['NaN']*len(ln_keys))[:len(ln_keys)]))
    hn = dict(zip(hn_keys,([x for sl in hn for x in sl]+['NaN']*len(hn_keys))[:len(hn_keys)]))
    mp_slice.update(ln)
    mp_slice.update(hn)
    return mp_slice

def mkp(df, w=50, mode='vol', tick_size=1):
    for i in range(0, df.shape[0]-window+1):
        dfp = df[i:i+window]
        mp = MarketProfile(dfp, mode=mode, tick_size=tick_size)
        mp_slice = mp[dfp.index.min() : dfp.index.max()].as_dict()
        mp_slice = mp_dict(mp_slice, w=w)
        df = df.combine_first(pd.DataFrame(mp_slice, index=[dfp.index.max()]))
    df = df.apply(pd.to_numeric, errors='coerce')
    return df`

**Comment by NPattanaik1** [comment]
If there is any improvisation in the code till now..
