### ISSUE TITLE
upload data

### ISSUE THREAD

**Issue by stef30360** [bfolkens/py-market-profile#6]
HI 
I can't upload data , google.txt is created but it's empty ?
`if not os.path.exists('google.txt'):
    get_google_data('google.txt', 'GOOG', 60 * 30, 5)
    
df = read_google_data('google.txt')`
regards 
SR

**Comment by bfolkens** [comment]
That data is retrieved from Google Finance, so I would check to see if Google is returning something invalid:

`curl "http://finance.google.com/finance/getprices?q=GOOG&i=1800&p=5d&f=d,o,h,l,c,v"`
